# Mission Failed

Et voilà, c’est arrivé : le produit sur lequel je travaillais a échoué, mort avec pertes et fracas. Que s’est-il passé ? Ce n’est évidemment pas la première fois qu’une intégration de progiciel dans un cycle en V échoue lamentablement. Tous les éléments classiques de l’échec étaient réunis : intégration de progiciel, guéguerres managériales, cycle en V non assumé, contractualisation à outrance, manque de délégation etc… il n’y aurait rien de plus à dire que ce qui a déjà été dit et qui a fait que l’agilité a émergé. Mais alors pourquoi ces échecs à plusieurs millions existent encore? Reprenons une discussion qui court sur plus de 50 ans sur le sujet de la gestion de projet et essayons de voir pourquoi il existe encore des décideurs qui choisiraient rationnellement une méthode prédictive dans des contextes complexes, et pourquoi c’est une erreur.

MISSION FAILED

#### Un échec cuisant, état des lieux

Après avoir développé un MVP, la MOE et la MOA s’engagent sur un cahier des charges à 3 ans. En attendant, les utilisateurs refusent de se servir du livrable en l’état. La MOA insiste sur le fait que les délais devront être tenus et la MOE promet que les délais seront tenus. Quelques mois plus tard, le projet est arrêté.
Un an et demi de travail de plusieurs dizaines de personnes mis à la poubelle, plusieurs millions d’euros perdus, des prestataires sortis en catastrophe etc. Le bilan est lourd. Comment en est-on arrivés là? Le produit avait deux objectifs majeurs : rationaliser le développement d’offres de plusieurs départements et améliorer sensiblement le Time To Market. Comment? En intégrant un progiciel qui promettait assez de souplesse pour pouvoir créer une offre d’assurance en moins de 3 mois.
Un an et demi et un REX plus tard, ce fiasco serait dû à de mauvais choix techniques, des erreurs de management et d’organisation en général. Mais un point a particulièrement retenu mon attention : comment ce fait-il qu’en 2019 on puisse encore développer des produits complexes avec une approche prédictive et un cahier des charges sur 3 ans?

#### Un échec cuisant : le plan à 3 ans

En reprenant l’état du backlog au temps t et le débit d’items livrées en moyenne par semaine par les équipes, une première projection me donnait un travail restant à faire à plus de 6 mois, alors que tout devait être terminé. Cela n’empêcha pas les décideurs de demander un cahier des charges qui contiendra plus de 150 fonctionnalités planifiées sur 3 ans. Puisqu’on considérait que l’utilisateur ne pouvait pas utiliser une application qui ne serait pas « complète », et puisque les mises en production se font tous les 6 mois, chaque partie prenante chargeait au maximum ses fonctionnalités de peur de rater le train et de devoir attendre de longs mois. Ainsi s’est formé un plan détaillé avec ses livrables, ses jalons, le tout jusqu’en 2021. Une date qui évidemment allait être tenue, puisqu'elle devait être tenue, selon les principes de M. Coué. S’il y eut des tentatives d’adoucir ce monolithe, elles furent réduites à néant par les engagements contractuels. Heureusement, la mascarade fut arrêtée suffisamment tôt pour éviter des pertes encore plus importantes. Au delà de l’état de fait, qu’est-ce qui pourrait soutenir l’efficacité de l’utilisation de cahier des charges à plusieurs années ?

#### La Hiding Hand : principe

Dans une publication de 1967 appelé « The principle of the Hiding Hand », l’économiste Albert O. Hirschman expose comment, selon lui, il est bon de planifier à long terme sur de gros projets et de se tromper sur ses prédictions. Le principe qu’il appelle la Hiding Hand forcerait les décideurs à rencontrer des difficultés non prévues et à s’y adapter, les transformant en entrepreneurs capables de prises de risque. Il explique que l’erreur de planification s’explique selon 2 modes : la pseudo-imitation et le pseudo-programme-complet. La pseudo-imitation fait croire au décideur qu’un modèle ayant déjà été appliqué avec succès ailleurs, pourra donc se dérouler sans problème majeur ici avec un ratio de 90/10 entre le pareil et le différent. Hirschman nous explique qu’en fait ce ratio se retrouve souvent inversé avec 90% de spécifique, et donc de différent, et 10% de pareil. On retrouve typiquement ce mode dans l’intégration de progiciel, avec la promesse du ratio entre ce qui est disponible sur étagère et ce qui reste de spécifique à développer.
Le second mode qui permet la Hiding Hand est le pseudo-programme-complet. Ici le décideur prend pour argent comptant le discours de l’expert qui planifie les étapes, un budget, les personnes impliquées, le matériel à déployer, le tout sur plusieurs années; en bref un programme exhaustif qu’il suffira de dérouler pour aboutir au succès du projet. L’application du plan dévoilera bien souvent que cette expertise était en fait l’équivalent d’une boule de Crystal et que ses prédictions ne se dérouleront pas comme annoncées. Toute personne ayant une expérience d’un cycle en V d’au moins 6 mois sur un projet informatique reconnaitra le mode pseudo-programme-complet.
En résumé, le mode « pseudo-imitation » fait apparaitre un projet comme moins difficile, et le mode « pseudo-programme-complet » donne l’illusion aux décideurs qu’ils peuvent déjà savoir ce qu’il va se passer. Et ils sont tout à fait compatibles sur un même projet.
Hirschman considère que ces deux modes entrainent bien des difficultés par leurs erreurs d’appréciation, mais que c’est dans cette adversité que les décideurs seront forcés d’être créatifs et de prendre des décisions pertinentes et rapides, en résumé de s’adapter comme dans la fameuse maxime de Nietsche : « ce qui ne te tue pas te rend plus fort ».

#### L’exemple de l’usine de bambou pakistanaise

Hirschman donne l’exemple d’une grosse exploitation de bambou située dans un Pakistan au sortir de l’indépendance. Après quelques déboires techniques, l’usine était prête à fonctionner et exploiter les centaines d’hectares de bambou au milieu desquels elle était installée. Mais suite à une rarissime floraison du bambou le bois fut rendu inexploitable et l’usine s’est retrouvée sans matière première. Rapidement, les responsables lancèrent des recherches pour identifier une autre espèce de bambou qui soit fiable et dont la pousse est rapide, et ils arrivèrent ainsi à se sortir de ce guêpier et même à dépasser les prévisions de départ. Les décideurs avaient donc surestimé la disponibilité de matière première, mais ils avaient aussi sous-estimé leur capacité d’adaptation. C’est dans ce mécanisme que se déploie la Hiding Hand.
On peut retrouver des exemples similaires dans l’informatique. Citons l’entreprise Ludicorp qui, confrontée au manque d’intérêt suscité par le jeu vidéo qu’ils développaient, ont dû s’adapter et ont créé une application web d’échange de photos très populaire: Flickr.
Alors si la Hiding Hand fonctionne, pourquoi mon dernier projet a-t-il échoué ?

#### Le problème statistique

En 2014, Bent Flyvbjerg et Cass R. Sunstein répondent à Hirschman dans une publication nommée « The principle of the Malevolent Hiding Hand; or, the Planning Fallacy Writ Large ». Ils éprouvent la Hiding hand en confrontant statistiquement ses résultats. Ils observent d’abord que Hirschman ne compile que 11 projets dans sa démonstration, ce qui est évidemment trop faible pour prouver un phénomène général. Ils entreprennent donc d’étudier 2062 grands projets et leur réussite au regard de leur coût prévu et de leur bénéfice final. Si Hirshman a raison, on devrait observer que les projets dont les coûts sont sous-évalués devraient voir leurs hausses de bénéfices largement compenser ces pertes grâce à la créativité de leurs décideurs.
Qu’en est-il? Non seulement les bénéfices ne compensent que très rarement les coûts, mais il n’y a en moyenne pas de hausse des bénéfices du tout. Les auteurs décrivent une Hiding Hand malveillante : les erreurs de planification ne sont pas couverts par une créativité émergente qui soit n’arrive pas, ou bien trop tard, ou bien qui n’est simplement pas suffisante. Cette Hiding Hand malveillante est observée 3,5 fois plus que la Hiding Hand bienveillante, ce qui les conduit à la conclusion suivante : la Hiding Hand est un cas particulier et un plan optimiste n’est pas une condition suffisante à la réussite d’un projet.

#### Se faire mal, mais pas trop mal

En reprenant ce dialogue d’économistes sur un demi siècle, j’ai cherché à trouver ce qui pourrait encore justifier, dans l’industrie logicielle, l’utilisation des méthodes prédictives dans un environnement complexe. En dehors des problématiques de contractualisation ou de psychologie (comme l’habitude ou le biais d’optimisme comparatif), qu’est-ce qui pourrait expliquer qu’on utilise encore des Cycles en V dans des développements logiciels complexes? Tout le monde convient qu’il est difficile de planifier la création d’un logiciel sur 3 ans, et que les béquilles que sont la «pseudo-imitation » et le « pseudo-programme-complet » sont des illusions dangereuses. Et il apparaît d’après Flyvbjerg et Sunstein que se sortir d’une planification fallacieuse est statistiquement difficile. Je repense aux mots d’un des décideurs de mon projet râté: « on contractualise un planning sur 3 ans, avec une variation maximum de 20% sur les jalons ». Mais pourquoi rigidifier le poids de la planification dans une industrie, le logiciel, où nous avons la chance de travailler un produit suffisemment souple et évolutif pour pouvoir faire des choix et s’adapter -dans certaines limites- tout au long du développement? Le but de la « main cachante » est de rendre les décideurs plus créatifs et plus capables de prise de risque; et c’est précisément ce que propose l’empirisme, en essayant puis en analysant le résultat. On peut allier de cette manière des essais audacieux à une prise de risque mesurée.
Dans un an le Manifeste Agile aura 20 ans, et pourtant l’oubli de sa quatrième valeur « l’adaptation au changement plus que le suivi d’un plan » aura encore conduit à l’échec d’un projet. Nous n’avons pas besoin une mauvaise planification : nous avons l’empirisme. Les méthodes prédictives avec une planification rigide sont dangereuses? Heureusement nous pouvons accompagner le changement! Nous voulons fabriquer des acteurs entreprenants, nous avons le terrain de jeu pour essayer. J’ai une vision, un objectif, et j’avance pas à pas en m’inspectant et en m’adaptant régulièrement.
Photo : WHY NOT BOTH?

#### Never say never again

L’inspection et l’adaptation ne sont évidemment pas les conditions suffisantes à la réussite d’un logiciel complexe, mais elles en sont les conditions nécessaires. Ce sont elles qui permettent de prendre les risques qui permettront d’avancer, au pire en se faisant mal mais jamais « trop » mal. L'optimisme naïf de la Hiding Hand d'Hirschman n'apporte manifestement pas de solution intéressante, mais elle décrit étonnament bien 2 modes d'échecs courants des méthodes prédictives.
Je voulais conclure en partageant un contre exemple à cet échec. Il y a quelques années un projet de compteurs électriques communicants était lancé en fanfare. Les attentes étaient fortes. Un département majeur de ce SI démarra le projet comme il savait le faire : MOA, MOE, cahier des charges sur plusieurs années etc… Mais au bout d’un an, les indicateurs étaient au rouge. Le directeur du département était expérimenté et il pressentait l’échec à venir du projet. Il prit donc une décision courageuse : changer de méthode, faire des itérations et livrer un premier service de bout en bout. Aujourd’hui plus de 13 millions de compteurs Linky fournissent de l’électricité à 50 millions de français.
